/**
 * Generated by webmcp-codegen — this file is fully regenerated on every run.
 * Do not edit by hand; your changes will be lost.
 */

/** The result shape tools return (same as MCP tool results). */
export interface WebMcpToolResult {
  content: { type: "text"; text: string }[];
  [key: string]: unknown;
}

/** A tool as the browser runtime understands it. */
export interface WebMcpToolDefinition {
  name: string;
  description: string;
  inputSchema?: Record<string, unknown>;
  execute: (input: Record<string, unknown>) => unknown | Promise<unknown>;
}

/** The slice of the WebMCP draft spec the generated code uses. */
export interface ModelContext {
  registerTool(
    tool: WebMcpToolDefinition,
    options?: { signal?: AbortSignal },
  ): Promise<void>;
}

/**
 * Access the page's WebMCP model context, with a helpful error when the
 * browser doesn't have one (rather than an undefined-callsite mystery).
 */
export function getModelContext(): ModelContext {
  const modelContext = (document as unknown as { modelContext?: ModelContext }).modelContext;
  if (!modelContext) {
    throw new Error(
      "WebMCP is not available in this browser. " +
        "Enable chrome://flags/#enable-webmcp-testing (Chrome 146+), " +
        "or add the WebMCP polyfill to your app.",
    );
  }
  return modelContext;
}

/**
 * Default "agent proposes, human confirms" gate for write/destructive tools.
 * Deliberately minimal (window.confirm) — replace it with your app's own
 * dialog when you outgrow it. The point is that the user always gets a say.
 */
export function requestUserConfirmation(message: string): Promise<boolean> {
  return Promise.resolve(window.confirm(message));
}
