/**
 * Generated by webmcp-codegen. This file is fully regenerated on every run.
 * Import registerAllTools() once at app startup:
 *
 *   import { registerAllTools } from "./webmcp";
 *   await registerAllTools();
 */

import { registerGetAllAlbums } from "./get-all-albums.webmcp";
import { registerCreateAlbum } from "./create-album.webmcp";
import { registerGetAlbumInfo } from "./get-album-info.webmcp";
import { registerDeleteAlbum } from "./delete-album.webmcp";
import { registerGetAssetInfo } from "./get-asset-info.webmcp";
import { registerCreateUserAdmin } from "./create-user-admin.webmcp";

const registrations = [
  registerGetAllAlbums,
  registerCreateAlbum,
  registerGetAlbumInfo,
  registerDeleteAlbum,
  registerGetAssetInfo,
  registerCreateUserAdmin
];

/**
 * Register every generated tool with WebMCP. One tool failing (for example
 * because the page's Permissions-Policy disables tools) never takes the
 * others down with it. The failure is logged and registration continues.
 */
export async function registerAllTools(signal?: AbortSignal): Promise<void> {
  for (const register of registrations) {
    try {
      await register(signal);
    } catch (error) {
      console.warn("[webmcp-codegen] a tool failed to register:", error);
    }
  }
}
