// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/docs/troubleshooting.mdx?collection=docs&hash=1787770219410"
import * as docs_7 from "../content/docs/safety.mdx?collection=docs&hash=1787770219410"
import * as docs_6 from "../content/docs/regeneration.mdx?collection=docs&hash=1787770219410"
import * as docs_5 from "../content/docs/quickstart.mdx?collection=docs&hash=1787770219410"
import * as docs_4 from "../content/docs/index.mdx?collection=docs&hash=1787770219410"
import * as docs_3 from "../content/docs/guides.mdx?collection=docs&hash=1787770219410"
import * as docs_2 from "../content/docs/devtools.mdx?collection=docs&hash=1787770219410"
import * as docs_1 from "../content/docs/configuration.mdx?collection=docs&hash=1787770219410"
import * as docs_0 from "../content/docs/cli.mdx?collection=docs&hash=1787770219410"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"cli.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/cli.mdx"}, data: docs_0 }, { info: {"path":"configuration.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/configuration.mdx"}, data: docs_1 }, { info: {"path":"devtools.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/devtools.mdx"}, data: docs_2 }, { info: {"path":"guides.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/guides.mdx"}, data: docs_3 }, { info: {"path":"index.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/index.mdx"}, data: docs_4 }, { info: {"path":"quickstart.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/quickstart.mdx"}, data: docs_5 }, { info: {"path":"regeneration.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/regeneration.mdx"}, data: docs_6 }, { info: {"path":"safety.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/safety.mdx"}, data: docs_7 }, { info: {"path":"troubleshooting.mdx","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/troubleshooting.mdx"}, data: docs_8 }], [{"info":{"path":"meta.json","absolutePath":"/Users/souravinsights/Documents/Personal/webmcp-stack/site/content/docs/meta.json"},"data":{"title":"webmcp-stack","pages":["index","quickstart","cli","configuration","safety","regeneration","guides","devtools","troubleshooting"]}}])