"use client";

import { useState } from "react";
import { DEMO_SOURCE, DEMO_TOOLS } from "@/lib/demo-data";

/* The landing page demo. The endpoints come from a real open-source
   project's OpenAPI spec; the files were generated by the real CLI at
   build time (site/scripts/build-demo-data.mjs). Clicking an endpoint
   shows exactly what `npx webmcp-codegen generate` would write. */

const VERB_CLASS: Record<string, string> = {
  GET: "border-accent/40 text-accent",
  POST: "border-signal/40 text-signal",
  DELETE: "border-fault/40 text-fault",
};

const LABEL_CLASS: Record<string, string> = {
  read: "text-faint",
  write: "text-signal",
  destructive: "text-fault",
};

const KEYWORDS = new Set([
  "export", "const", "async", "function", "type", "return", "await", "new", "import", "from",
]);

/* Enough syntax color to read as code, not a highlighter. Strings amber,
   known keywords accent, comments ghost, everything else quiet. */
function CodeLine({ line }: { line: string }) {
  if (line.trimStart().startsWith("//")) {
    const isMarker = line.includes("───");
    return (
      <div className={isMarker ? "text-accent" : "italic text-ghost"}>
        {line}
      </div>
    );
  }
  const parts = line.split(/("(?:[^"\\]|\\.)*")/g);
  return (
    <div>
      {parts.map((part, i) =>
        part.startsWith('"') ? (
          <span key={i} className="text-signal">
            {part}
          </span>
        ) : (
          <span key={i} className="text-dim">
            {part.split(/\b/).map((word, j) =>
              KEYWORDS.has(word) ? (
                <span key={j} className="text-accent">
                  {word}
                </span>
              ) : (
                word
              ),
            )}
          </span>
        ),
      )}
    </div>
  );
}

export function LiveDemo() {
  const [selected, setSelected] = useState(0);
  const tool = DEMO_TOOLS[selected];

  return (
    <div className="border border-line bg-panel">
      {/* Chrome: what this is, with a link to the real spec. */}
      <div className="flex items-center gap-1.5 border-b border-line px-4 py-2.5">
        <span className="size-2 rounded-full bg-line" aria-hidden="true" />
        <span className="size-2 rounded-full bg-line" aria-hidden="true" />
        <span className="size-2 rounded-full bg-line" aria-hidden="true" />
        <span className="ml-2 font-mono text-[11px] text-ghost">
          {DEMO_SOURCE.project}, {DEMO_SOURCE.blurb}
        </span>
        <a
          href={DEMO_SOURCE.specUrl}
          className="ml-auto font-mono text-[11px] text-faint transition-colors duration-150 hover:text-ink"
          style={{ transitionTimingFunction: "var(--ease-reading)" }}
        >
          real spec →
        </a>
      </div>

      <div className="grid lg:grid-cols-[minmax(0,2fr)_minmax(0,3fr)]">
        {/* Endpoint list: the spec side. */}
        <div className="max-h-56 min-w-0 overflow-y-auto border-b border-line lg:max-h-none lg:border-b-0 lg:border-r">
          {DEMO_TOOLS.map((t, i) => (
            <button
              key={t.name}
              type="button"
              onClick={() => setSelected(i)}
              className={`flex w-full items-center gap-3 px-4 py-3 text-left transition-colors duration-150 ${
                i === selected ? "bg-panel-raised" : "hover:bg-panel-raised/50"
              } ${i > 0 ? "border-t border-line" : ""}`}
              style={{ transitionTimingFunction: "var(--ease-reading)" }}
            >
              <span
                className={`shrink-0 border px-1.5 py-0.5 font-mono text-[10px] ${VERB_CLASS[t.verb] ?? "border-line text-dim"}`}
              >
                {t.verb}
              </span>
              <span className="min-w-0 flex-1">
                <span className="block truncate font-mono text-[12px] text-ink">{t.path}</span>
                <span className="block truncate text-[11.5px] text-faint">{t.summary}</span>
              </span>
              <span className={`shrink-0 font-mono text-[10.5px] ${LABEL_CLASS[t.sideEffect]}`}>
                [{t.sideEffect}]
              </span>
            </button>
          ))}
        </div>

        {/* Generated file: the output side. */}
        <div className="min-w-0">
          <p className="truncate border-b border-line px-4 py-2 font-mono text-[11px] text-ghost">
            src/webmcp/{tool.fileName}
          </p>
          <pre className="max-h-96 overflow-auto px-4 py-4 font-mono text-[11px] leading-relaxed sm:text-[11.5px] lg:max-h-[26rem]">
            {tool.fileCode.split("\n").map((line, i) => (
              <CodeLine key={i} line={line} />
            ))}
          </pre>
        </div>
      </div>
    </div>
  );
}
